### ISSUE TITLE
Module just shows loading

### ISSUE THREAD

**Issue by gnwoodward** [jackmeyer/MMM-SleeperNFL#1]
I've added the MMM-SleeperNFL module, added my ID's and I did some fiddling to get it to at least show my league name.
After that it just says Loading with nothing ever happening. 
It will say "League Name" so I know it's picking up that ID. I've tried alternating userID & userName to no avail. 
Anyone else having success with this module?

Thanks!

**Comment by jackmeyer** [comment]
Thanks for reaching out, I haven’t looked at this module since last football season and it’s possible that the Sleeper API might have changed since then. Or there’s a hardcoded value somewhere messing things up. I just did my league’s draft today so I’ll look at this issue in the next few days.

**Comment by gnwoodward** [comment]
Appreciate it! 
Like I mentioned - it did pull the league name so I'm not sure if something changed with the UserID field. 
I'll look forward to any updates! Good luck this year - my first time using Sleeper and so far I love every aspect of it. Now I just need to get it on my MM. Would love to have my team side by side with my wife's team.

**Comment by jackmeyer** [comment]
I think the issue is that Sleeper's API hasn't yet considered the new season as "started" yet. The API call to get matchup data for your league only takes `week` as a parameter, so when it's getting called with week 1, it's still looking for last season. My module works at the moment, but it's pulling week 1's matchup from LAST year. 

If you [take a look yourself](https://api.sleeper.app/v1/state/nfl), Sleeper says the season officially starts 09-07-2023. I would guess that the module will automagically start working on the 7th. I might figure out a workaround before then, but we'll see. 

I'm just glad to see someone else using this <3 I'll make sure to get it working.

**Comment by jackmeyer** [comment]
@gnwoodward just checking in, my module is fully working as expected, without me making any changes.

I actually didn't realize that the leagueID changes, even if you renew the "same" league for another season. Once I dropped in my new league ID, i'm getting the full matchup details. Not sure if it's just because it's September 7th, or because I changed my league ID, but it's all there now.

![image](https://github.com/jackmeyer/MMM-SleeperNFL/assets/29171130/e5ccaa43-4756-42ba-acd8-b01f361d57f5)

**Comment by gnwoodward** [comment]
No dice for me. Still only shows "League Name Week 1" (League Name is
correct)
I've tried updating my userID and LeagueID but no changes.

League name and userId is in quotes, correct?

{
        module: 'MMM-SleeperNFL',
        disabled: false,
        position: 'top_right',
        config: {
        userId: "998424930326917120", //required
        leagueId: "998426289038118912", //required
        showBench: false, //optional, default: true
        showPlayerAvatars: false, //optional, default: true
                tableSize: 'xsmall', //optional, default: 'small'
('xsmall', 'small', 'medium')
                liveInterval: 60000, //optional, default: 30000 (30 seconds)
                inactiveInterval: 300000 //optional, default: 5minutes (in
milliseconds)
        }

**Comment by jackmeyer** [comment]
Hey @gnwoodward, I started from a blank slate, using your config, and found the issue. Looks like the playerlist.json file wasn't updating for some reason, so it was failing to find rookies, and was crashing.

I've pushed an updated list, try running `git pull` in the MMM-SleeperNFL folder, then launch MM again.
